### ISSUE TITLE
Is it possible to cut a solid into two piece by NURBS surface in pivy?

### ISSUE THREAD

**Issue by cbjcbj** [coin3d/pivy#4]
Hi, I am working on the pivy lib these days and find it really realy useful. Especially thanks to your mentor examples! And I wonder if it is possible to cut a solid, such as a tetrahedron into two pieces, by a surface describe in the NURBS manner. Thank you!

**Comment by looooo** [comment]
I don't know if this is possible. Example 08.4 shows how to trim a bezier surface. But I never used something like this.

**Comment by cbjcbj** [comment]
Oh, thank you. I didn't notice your reply before! I will take a look at the example, Thank you very much:)
