### ISSUE TITLE
pivy 0.6.4: "checking for SOQT via cmake" fails under MacPorts

### ISSUE THREAD

**Issue by Schamschula** [coin3d/pivy#56]
I'm trying to upgrade the MacPorts Portfile to version 0.6.4. (version 0.6.2 is currently available).

Unfortunately, the cmake check for SOQT fails. On further investigation, I find that there is no `FindSoQt.cmake` file provided by the SoQt port.

**Comment by looooo** [comment]
This needs a recent state of the soqt-library build with cmake.

**Comment by Schamschula** [comment]
Recent state?

On Bitbucket the most recent version is SoQt 1.5.0 from 2012. No sign of cmake anywhere!

**Comment by Schamschula** [comment]
It looks like Coin and SoQt have to be built from mercurial to provide cmake support.

This is a problem, as there is no fixed source state and there are no checksums. Fine for development, useless for release. It would be useful to have a more current release of both packages.

**Comment by Schamschula** [comment]
I built and installed Coin (4.0.0) and SoQt (1.6.0) from hg using cmake. Unfortunately, pivy still refuses to admit that SoQt is installed.

**Comment by rubendibattista** [comment]
Ehi @Schamschula, I managed to update Coin and SoQt [here](https://github.com/rubendibattista/macports-ports/tree/freecad) and `pivy` recognizes SoQt successfully. Now, unfortunately, I'm struggling with `swig` not find standard headers...

**Comment by rubendibattista** [comment]
Ok, #46 is related. Now `pivy` builds correctly :). I'll push a PR soon on MacPorts.

**Comment by luzpaz** [comment]
@rubendibattista status on that?  
Can this ticket be closed?

**Comment by rdbisme** [comment]
I don't think I managed to solve it fully. So this should stay open but at the moment I have no bandwith to keep on working on this.

**Comment by looooo** [comment]
I am soon trying to create a 0.6.6 release. Would be nice to have this fixed.

**Comment by Schamschula** [comment]
As part of updating FreeCAD to version 0.19, I'm in the process of updating the Coin/Coin-framework port to 4.0.0. I then need to test all the other dependents.

**Comment by looooo** [comment]
As we have switched to cmake, I guess this one is outdated. Feel free to reopen @Schamschula
