### ISSUE TITLE
Why not using cmake for everything? 

### ISSUE THREAD

**Issue by rubendibattista** [coin3d/pivy#59]
Is there any special reason to use `distutils` (in which you partially use `cmake` to retrieve `soqt` and `coind` paths) instead of `cmake` for everything? 

Your `setup.py` doesn't take care of lots of corner case (for example on macOS where `qmake` is not available in the `PATH` if installed with Macports) and it assumes a standard configuration that is not really standard for most users. Using `cmake` would standardize most of the stuff that now is hacked in the `setup.py`and partially buggy...

**Comment by looooo** [comment]
It would be fantastic to Port the configuration to cmake.

**Comment by kkremitzki** [comment]
Agreed that this is a good goal for 0.6.6.

**Comment by looooo** [comment]
0.6.6 released with cmake support. So we can close this one.

**Comment by rdbisme** [comment]
Thanks!
