### ISSUE TITLE
Could not find a package configuration file provided by "Coin"

### ISSUE THREAD

**Issue by leoheck** [coin3d/pivy#94]
Hi, I am trying to build privy myself trying to fix an issue I am having with FreeCad with the Image Scaling that is complaining of something.

Then building it on my new (pre-released) Ubuntu 22.04 I am seeing this issue.
I don't know much about this `Coin` and it looks a pretty generic name to look for in Google. What is it? I want to understand this, to be able to solve this issue with this missing package. 

```cmake
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a package configuration file provided by "Coin" with any of
  the following names:

    CoinConfig.cmake
    coin-config.cmake

  Add the installation prefix of "Coin" to CMAKE_PREFIX_PATH or set
  "Coin_DIR" to a directory containing one of the above files.  If "Coin"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by waebbl** [comment]
Looks like you don't have coin3d installed (https://github.com/coin3d/coin).
You might take a look at https://launchpad.net/ubuntu/jammy/+source/coin3 or build it from scratch for yourself.

**Comment by leoheck** [comment]
Ok, so Coin is Coin3d, now it is a better keyword for finding a solution. Thanks @waebbl

**Comment by luzpaz** [comment]
should we close this ticket then?

**Comment by leoheck** [comment]
I could not build yet. But sure, I am closing this.
